name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build documentation
        run: npm run doc

      - name: Deploy to docs branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.NPM_GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: docs
          commit_message: ${{ github.event.head_commit.message }} 